### ISSUE TITLE
Bot requires verification

### ISSUE THREAD

**Issue by MDAMI** [darthdie/gmnitron#3]
Congratulations!

Your bot is in more than a 100 servers. I'd like to use it too but Discord requires GMnitron to be verified before it'll let any more people invite the bot to the server.

[Support page](https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting)

![image](https://user-images.githubusercontent.com/4349752/103142409-8dbc4580-46d0-11eb-9446-f15c0693ee61.png)

**Comment by darthdie** [comment]
Thanks for letting me know!

I worked on becoming verified, but unfortunately Discord doesn't allow "nitro" to appear in the name of a bot and so it didn't allow me to verify the bot. I'm currently working through a support ticket in hopes that I don't have to rename it.

**Comment by darthdie** [comment]
The bot's display name has been renamed to "GM-itron" to satisfy the verification process, and the process has been started.
